// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBuVOvaveGWaPSUMu9J4HrqMIK3Wzk3g',
    appId: '1:51739115622:web:1f501d12325e9973e0ada7',
    messagingSenderId: '51739115622',
    projectId: 'swishdb-b2abb',
    authDomain: 'swishdb-b2abb.firebaseapp.com',
    storageBucket: 'swishdb-b2abb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl641nkHsdKKNadxpZr8C3yWQTlkVIiNs',
    appId: '1:51739115622:android:d2f754083e882265e0ada7',
    messagingSenderId: '51739115622',
    projectId: 'swishdb-b2abb',
    storageBucket: 'swishdb-b2abb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8HvNZ-M77uRO-C54srgjXxLDjeHkIwA',
    appId: '1:51739115622:ios:8da2809d29c268cae0ada7',
    messagingSenderId: '51739115622',
    projectId: 'swishdb-b2abb',
    storageBucket: 'swishdb-b2abb.appspot.com',
    iosClientId: '51739115622-nni0i3cvetonuv4f60e40pgo6qd0tvla.apps.googleusercontent.com',
    iosBundleId: 'com.example.swish006',
  );
}
